/*
 Minified and unminified versions of this file are located in the same directory. Access unminified version by replacing the .min.js extension with .js WP and Divi Icons by Divi Space, an Aspen Grove Studios company
Licensed under the GNU General Public License v3 (see ../license.txt)

This plugin includes code based on parts of the Divi theme and/or the
Divi Builder, Copyright (c) Elegant Themes, licensed GPLv2+, used under GPLv3 (see ../license.txt).
*/
for(var agsdi_icons_loaded=[],wadi_config={parentIds:"#main-content, #et-main-area, #page-container, #et-boc",noBeforeElements:[["et_pb_main_blurb_image","et_pb_image_wrap"],["et_pb_shop"],["et_pb_comments_module"]],noAfterElements:[["et_pb_main_blurb_image","et_pb_image_wrap"],["et_pb_shop"],["et_pb_comments_module"],["et_overlay"],["et_font_icon","*"],["et_pb_main_blurb_image","et-pb-icon"],["et_pb_comments_module"],["et_pb_icon","et-pb-icon"],["et_pb_toggle_title"]],parentsAsClasses:[],observerEnabled:!0},
agsdi_svg_index=0,i=0;i<wadi_config.noBeforeElements.length;++i)2===wadi_config.noBeforeElements[i].length&&-1===wadi_config.parentsAsClasses.indexOf(wadi_config.noBeforeElements[i][0])&&wadi_config.parentsAsClasses.push(wadi_config.noBeforeElements[i][0]);for(i=0;i<wadi_config.noAfterElements.length;++i)2===wadi_config.noAfterElements[i].length&&-1===wadi_config.parentsAsClasses.indexOf(wadi_config.noAfterElements[i][0])&&wadi_config.parentsAsClasses.push(wadi_config.noAfterElements[i][0]);
window.agsdi_render_icons=function(k,n,p){function m(c,e,b){var a=jQuery(b),d=++agsdi_svg_index,g=[];a.attr("data-color1")&&g.push("#agsdi_svg_"+d+" .wadip-primary-color{fill:"+a.attr("data-color1")+";}");a.attr("data-color2")&&g.push("#agsdi_svg_"+d+" .wadip-secondary-color{fill:"+a.attr("data-color2")+";}");-1===e.indexOf("wadip-tertiary-color")||!a.attr("data-color3")&&jQuery(document.body).hasClass("et-fb")||g.push("#agsdi_svg_"+d+" .wadip-tertiary-color{fill:"+(a.data("color3")?a.attr("data-color3"):
"#ccc")+";}");g.length&&(a=e.indexOf(">"),-1!==a&&(e=e.substring(0,a)+' id="agsdi_svg_'+d+'"><style>'+g.join("")+";</style>"+e.substring(a+1)));a=jQuery(b);if(a.closest(".wp-block-paragraph, #tinymce, .mce-container-body, .wp-block-freeform").length){b=a.closest("body").siblings("head");d=a.attr("data-color1");g=a.attr("data-color2");var f=a.attr("data-color3");a=c+";"+(d?d:"")+";"+(g?g:"")+";"+(f?f:"");b.find('style[data-src="'+a+'"]:first').length||(c='[data-icon="'+c+'"]'+(d?'[data-color1="'+d+
'"]':":not([data-color1])")+(g?'[data-color2="'+g+'"]':":not([data-color2])")+(f?'[data-color3="'+f+'"]':":not([data-color3])"),b.append(jQuery("<style>").attr("data-src",a).text(".wp-block-paragraph "+c+",#tinymce "+c+",.mce-container-body "+c+", .wp-block-freeform "+c+"{background-image:url(data:image/svg+xml;base64,"+btoa(e)+");}")))}else a.html()!==jQuery("<div>").html(e).html()&&a.html(e)}var l=jQuery(k);l.find(".et-pb-icon:not([data-icon]),.et-pb-icon:not([data-icon])").each(function(){var c=
jQuery(this).text();"agsdi-"===c.substr(0,6)||"agsdix-"===c.substr(0,7)?jQuery(this).attr("data-icon",c).html("").addClass("agsdi-loaded"):jQuery(this).addClass("agsdi-loaded")});l.find(".et_pb_toggle_title").each(function(){var c=window.getComputedStyle(this,"before").content;'"\\a gsdix-'===c.substring(0,10)||'"\\a gsdi-'===c.substring(0,9)?c="a"+c.substring(4,c.length-1):"\\a gsdix-"===c.substring(0,9)||"\\a gsdi-"===c.substring(0,8)?c="a"+c.substring(3):'"agsdix-'===c.substring(0,8)||'"agsdi-'===
c.substring(0,7)?c=c.substring(1,c.length-1):"agsdix-"!==c.substring(0,7)&&"agsdi-"!==c.substring(0,6)&&(c='"\\agsdix-'===c.substring(0,9)||'"\\agsdi-'===c.substring(0,8)?c.substring(2,c.length-1):"\\agsdix-"===c.substring(0,8)||"\\agsdi-"===c.substring(0,7)?c.substring(1):null);jQuery(this).attr("data-icon")||jQuery(this).attr("data-icon",c).addClass("agsdi-loaded")});l.find("[data-icon]").addBack("[data-icon]").each(function(){if(this.className&&this.className.indexOf&&-1!==this.className.indexOf("i-agsdi")){for(var c=
this.className.split(" "),e="",b=0;b<c.length;++b){var a=c[b].trim();"i-agsdi"===a.substr(0,7)&&(e+=a+" ")}if(e){jQuery(this).removeClass(e);return}}a=jQuery(this);var d=a.attr("data-icon");if(6<d.length&&("agsdi-"===d.substr(0,6)||"agsdix-"===d.substr(0,7))){c="i-"+d.replace(/ /,"-");if(!n)for(a.addClass(c),b=0;b<wadi_config.parentsAsClasses.length;++b)a.closest("."+wadi_config.parentsAsClasses[b]).length&&a.addClass("agsdi-parent-"+wadi_config.parentsAsClasses[b]);if(window.wadi_icons&&window.wadi_icons[d]){c=
n?'[data-icon="'+d+'"]':"."+c;e="";for(b=a.parent().closest(wadi_config.parentIds);b.length;)e="#"+b.attr("id")+" "+e,b=b.parent().closest(wadi_config.parentIds);if(p||!agsdi_icons_loaded[e+c]){a=e+" "+c;var g="",f={};for(b=0;b<wadi_config.noBeforeElements.length;++b)2===wadi_config.noBeforeElements[b].length?(f[wadi_config.noBeforeElements[b][0]]||(a+=":not(.agsdi-parent-"+wadi_config.noBeforeElements[b][0]+")",f[wadi_config.noBeforeElements[b][0]]=[]),"*"!==wadi_config.noBeforeElements[b][1]&&f[wadi_config.noBeforeElements[b][0]].push(wadi_config.noBeforeElements[b][1])):
a+=":not(."+wadi_config.noBeforeElements[b][0]+")";for(notParent in f)if(f[notParent].length){g+=(g?",":"")+e+" "+c+".agsdi-parent-"+notParent;for(b=0;b<f[notParent].length;++b)g+=":not(."+f[notParent][b]+")";g+=":before"}var t=e+" "+c,q="";f={};for(b=0;b<wadi_config.noAfterElements.length;++b)2===wadi_config.noAfterElements[b].length?(f[wadi_config.noAfterElements[b][0]]||(t+=":not(.agsdi-parent-"+wadi_config.noAfterElements[b][0]+")",f[wadi_config.noAfterElements[b][0]]=[]),"*"!==wadi_config.noAfterElements[b][1]&&
f[wadi_config.noAfterElements[b][0]].push(wadi_config.noAfterElements[b][1])):t+=":not(."+wadi_config.noAfterElements[b][0]+")";for(notParent in f)if(f[notParent].length){q+=(q?",":"")+e+" "+c+".agsdi-parent-"+notParent;for(b=0;b<f[notParent].length;++b)q+=":not(."+f[notParent][b]+")";q+=":after"}b=a+":before,"+g+","+t+":after,"+q+'{content:"\\'+window.wadi_icons[d]+'"!important;';if(window.wadi_fonts)for(var h in window.wadi_fonts)if(0===d.indexOf(h)){"agsdix-fas"===h&&(b+="font-weight: 900!important;");
b+='font-family:"'+window.wadi_fonts[h]+'"!important;';break}b+="}\n";h=l.closest("html").find("#agsdi-icons-style");h.length||(h=jQuery('<style id="agsdi-icons-style">').appendTo(l.closest("#tinymce").length?l.closest("#tinymce").siblings("head:first"):"head:first"));h.append(b);p||(agsdi_icons_loaded[e+c]=!0)}}else h=null,"agsdix-mcip-"===d.substring(0,12)&&(b={uni:"ags-universal",lin:"ags-lineal",out:"ags-outline",mul:"ags-multicolor",han:"ags-hand-drawn",fil:"ags-filled",ske:"ags-sketch",tri:"ags-tri-color",
ele:"ags-elegant"},c=d.substring(12,15),b[c]&&(h=ags_divi_icons_config.pluginDirUrl+"/icon-packs/"+b[c]+"/multicolor/"+d.substring(16)+".svg")),h&&(window.wadi_svg_icons||(window.wadi_svg_icons={}),"undefined"===typeof window.wadi_svg_icons[d]?(window.wadi_svg_icons[d]={queue:[this],svg:null},jQuery.get(h,{},function(r){window.wadi_svg_icons[d].svg=r;-1!==r.indexOf("wadip-tertiary-color")?window.wadi_svg_icons[d].colors=3:-1!==r.indexOf("wadip-secondary-color")?window.wadi_svg_icons[d].colors=2:window.wadi_svg_icons[d].colors=
1;for(var u=0;u<window.wadi_svg_icons[d].queue.length;++u)m(d,r,window.wadi_svg_icons[d].queue[u]);window.wadi_svg_icons[d].queue=[]},"text")):window.wadi_svg_icons[d].svg?m(d,window.wadi_svg_icons[d].svg,this):window.wadi_svg_icons[d].queue.push(this))}})};
jQuery(document).ready(function(k){function n(e){var b=e.find(".et_pb_toggle_title:first");b.attr("data-icon",null).removeClass(b.attr("class").split(" ").filter(function(a){return"agsdi-loaded"===a||"i-agsdi"===a.substring(0,7)}));agsdi_render_icons(e)}var p=window.MutationObserver?window.MutationObserver:window.WebkitMutationObserver;p&&(new p(function(e){if(wadi_config.observerEnabled)for(var b=0;b<e.length;++b){var a=e[b];if(a.addedNodes&&a.addedNodes.length)for(var d=0;d<a.addedNodes.length;++d)if(3===
a.addedNodes[d].nodeType){var g=jQuery(a.target);if(g.hasClass("et-pb-icon")){var f=g.text().trim();f&&"#"!==f[0]&&(g.attr("data-icon",f),"agsdi"!==f.substr(0,5)||document.getElementById("et-fb-app")||g.html(""),agsdi_render_icons(g.parent()))}}else agsdi_render_icons(jQuery(a.addedNodes[d]));else if("attributes"===a.type)d=a.target.getAttribute("data-icon"),!d||a.target.className&&-1!==a.target.className.indexOf("i-"+d.replace(/ /,"-"))?"class"===a.attributeName&&a.oldValue&&-1!==a.oldValue.indexOf("agsdi-loaded")?
k(a.target).addClass("agsdi-loaded"):"class"===a.attributeName&&(-1!==a.target.className.indexOf("et_pb_toggle_open")&&-1===a.oldValue.indexOf("et_pb_toggle_open")||-1!==a.target.className.indexOf("et_pb_toggle_close")&&-1===a.oldValue.indexOf("et_pb_toggle_close"))?n(k(a.target)):("data-color1"===a.attributeName||"data-color2"===a.attributeName||"data-color3"===a.attributeName)&&agsdi_render_icons(a.target):agsdi_render_icons(a.target);else if(a.removedNodes.length)for(d=0;d<a.removedNodes.length;++d){if(a.removedNodes[d].tagName&&
"svg"!==a.removedNodes[d].tagName.toLowerCase()){agsdi_render_icons(jQuery(a.target).parent());break}}else"characterData"===a.type?a.target.parentNode&&"STYLE"===a.target.parentNode.tagName&&(a=k(a.target).closest(".et_pb_module.et_pb_toggle"),a.length&&n(a)):agsdi_render_icons(jQuery(a.target).parent())}})).observe(document.body,{childList:!0,subtree:!0,attributeOldValue:!0,characterData:!0,attributeFilter:["data-icon","data-color1","data-color2","data-color3","class"]});k("#et-boc").on("mouseover mouseout",
".et_pb_toggle",function(){n(k(this))});if(window.wadi_fonts){var m=k("#agsdi-icons-style");m.length||(m=jQuery('<style id="agsdi-icons-style">').appendTo(k("head")));m.append("html:before { content: 'a'; position: absolute; top: -999px; left: -999px; }");var l=[],c=setInterval(function(){for(iconPrefix in wadi_fonts)if(-1===l.indexOf(wadi_fonts[iconPrefix])){m.append('html:before { font-family: "'+wadi_fonts[iconPrefix]+'"; }');l.push(wadi_fonts[iconPrefix]);return}clearInterval(c)},300)}agsdi_render_icons(k("body"))});
